### ISSUE TITLE
callback will not thrown when given file is "invalid"?

### ISSUE THREAD

**Issue by etwillbefine** [gquental/node-annotation#5]
hey,

here is an example of the problem:

``` js
require('annotation')('/home/projects/project1/sample/sample.js', console.log);
require('annotation')('/home/projects/project1/sample/benchmark.js', console.log);
```

`sample.js` is a file which contains annotated methods. 
`benchmark.js` is a regular js file without any annotations

The first `console.log` will be executed and prints out the reader object.
But the second one, where the file content should actually be "ignored" does not becomes executed.

Is there any way to fix it?
It seems like that in this case, no files will be processed anymore.

Another "bug" I found is the [`.toString` call](https://github.com/gquental/node-annotation/blob/master/src/Reader/File.js#L28) on data. Can you add a check, to test whether `data` is not null?

Regards

**Comment by gquental** [comment]
Hello!

Thanks for your feedback, during this week I will tackle this problem and get back to you as soon it's fixed!

Sorry for the delay, was really a lot do to in my work hehehe ;)

Best!

**Comment by etwillbefine** [comment]
Hey, are there any updates available? Could you figured out what happend there? 
Would be great to hear from you soon. Regards.
